nodeLinker: pnp

packageExtensions:
  "@etchteam/storybook-addon-status@*":
    peerDependencies:
      react-dom: "*"
      regenerator-runtime: "*"
  "@mdx-js/loader@*":
    peerDependencies:
      react: "*"
  "@storybook/addons@*":
    peerDependencies:
      react-dom: "*"
      regenerator-runtime: "*"
  "@storybook/api@*":
    peerDependencies:
      react-dom: "*"
  "@storybook/core@*":
    peerDependencies:
      webpack: "*"
  "@storybook/react@^6.2.9":
    peerDependencies:
      "@storybook/builder-webpack5": ^6.2.9
  eslint-config-canonical@*:
    peerDependencies:
      "@babel/core": "*"
  react-dev-utils@*:
    peerDependencies:
      typescript: "*"
      webpack: "*"
  storybook-addon-performance@*:
    peerDependencies:
      react-is: "*"
  storybook-addon-performance@^0.15.2:
    dependencies:
      tslib: ^2.0.1
  storybook-addon-turbo-build@^1.0.0-beta.0:
    dependencies:
      webpack: ^5.30.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@ojkelly/plugin-build.cjs
    spec: "https://yarn.build/latest"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: "@yarnpkg/plugin-stage"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
